Add error code descriptions
Zubax/kucher pull request #28
Opened 2019-07-09 12:55 UTC by loicgilbert

Closes #22

2019-07-10 03:31 UTC, pavel-kirienko requested changes

2019-07-10 03:31 UTC, pavel-kirienko commented on kucher/view/main_window/telega_control_widget/task_specific_status_widget/fault_status_widget.py
> +import yaml
Please move the third-party import above the local imports, as required by PEP8 (standard first, then third-party, then local). In this case, it should be either above or under the PyQt5 import group.

Also, is PyYAML does not seem to be listed as a dependency.

2019-07-10 03:31 UTC, pavel-kirienko commented on kucher/view/main_window/telega_control_widget/task_specific_status_widget/fault_status_widget.py
> +        file_name = 'kucher/view/main_window/telega_control_widget/task_specific_status_widget/error_codes.yml'
A hard-coded path is never a good idea. Please use a relative path like:

```python
importlib.Path(__file__).absolute().parent / 'error_codes.yaml'
```

2019-07-10 03:31 UTC, pavel-kirienko commented on kucher/view/main_window/telega_control_widget/task_specific_status_widget/fault_status_widget.py
> +                error_description = d
This code gets the job done but you should be aware that the `dict` class provides a method `get()` which can default to a predefined value if the key is not found:

```python
failed_task_name = str(tssr.failed_task_id).split('.')[-1]
error_description = error_codes[failed_task_name].get(tssr.failed_task_exit_code, 'unknown error')
```

2019-07-10 03:32 UTC, pavel-kirienko commented
@dimracer could you please have a look at the error code descriptions when you're back from California? This is not urgent.

2019-07-12 04:26 UTC, pavel-kirienko commented
Great. One last thing to fix is to list PyYAML in requirements.txt, then we should wait for Dmitry to confirm that the descriptions are okay.

2019-07-12 11:25 UTC, pavel-kirienko submitted a review, later dismissed

2019-07-16 01:43 UTC, dimracer commented
It would be better to extend the error description with comments. For example, "Motor model parameters are invalid. Check the motor parameters and perform the motor identification procedure."

2019-07-23 02:43 UTC, pavel-kirienko requested changes

2019-07-23 02:43 UTC, pavel-kirienko commented on kucher/view/main_window/telega_control_widget/task_specific_status_widget/fault_status_widget.py
> +        o.setStyleSheet("border: 0px;")
I would prefer to have it look like a regular bordered text box, like the line display above it but multi-line. Currently, the text is rendered like a regular label, so it's easy to mistake it for part of the GUI structure as opposed to an informational message.

2019-07-23 02:43 UTC, pavel-kirienko commented on kucher/view/main_window/telega_control_widget/task_specific_status_widget/fault_status_widget.py
> +        o.setFont(font)
Let's not make it monospace; it's not code we're displaying, but regular human-readable text.

2019-07-23 02:43 UTC, pavel-kirienko commented on kucher/view/main_window/telega_control_widget/task_specific_status_widget/fault_status_widget.py
> +        self._error_description_display = self._make_line_display()
Can we please make this one non-monospace, too?

2019-07-23 02:43 UTC, pavel-kirienko commented on kucher/view/main_window/telega_control_widget/task_specific_status_widget/fault_status_widget.py
> +        error_comment = error.get('comment', '') if type(error) is dict else ''
```suggestion
        error_comment = error.get('comment', '') if isinstance(error, dict) else ''
```

Applies to the line above as well. Your version breaks for subclasses.

2019-07-29 23:47 UTC, pavel-kirienko commented
@loicgilbert nudge

2019-07-29 23:50 UTC, pavel-kirienko commented
Nvm, I see the change now. Can we please keep other text fields monospace and only make the error description non-monospace?

2019-07-30 07:21 UTC, pavel-kirienko commented
We're now back to where we started, `_error_description_display` is still monospace. Also see my old comment about `isinstance`.

2019-07-30 08:12 UTC, pavel-kirienko approved these changes

2019-07-30 08:13 UTC, merged