Fix some dependencies
Zubax/kucher pull request #48
Opened 2022-06-16 20:42 UTC by silverv

This is not ready for merge yet

2022-06-17 07:33 UTC, pavel-kirienko reviewed
Nice. I see that Construct is still a submodule rather than a pip dependency.

2022-06-17 07:33 UTC, pavel-kirienko commented on .gitmodules
> +	url = https://github.com/silverv/qasync.git
Unless you introduced custom patches, let us use the upstream here.

2022-06-17 07:33 UTC, pavel-kirienko commented on kucher/__init__.py
>      os.path.join(THIRDPARTY_PATH_ROOT, 'quamash'),
```suggestion
```

2022-06-17 08:38 UTC, silverv commented on .gitmodules
> +	url = https://github.com/silverv/qasync.git
introduced one change

2022-06-17 08:47 UTC, pavel-kirienko commented on .gitmodules
> +	url = https://github.com/silverv/qasync.git
Okay. See Slack, your patch is not required, please make this point upstream.

2022-06-20 08:44 UTC, pavel-kirienko commented
Did you apply Black to all files in this PR? I see a lot of trivial formatting changes across the codebase.

2022-06-20 09:49 UTC, silverv commented
> Did you apply Black to all files in this PR? I see a lot of trivial formatting changes across the codebase.

Yes, to the files of Kucher not the libraries

2022-06-20 09:52 UTC, pavel-kirienko commented
Runs fine on clean Windows 11

<img width="963" alt="image" src="https://user-images.githubusercontent.com/3298404/174576167-1126983e-2dc4-4735-a2cb-102b17682d05.png">

2022-06-20 10:33 UTC, pavel-kirienko requested changes
Intermediate review, will continue later

2022-06-20 10:33 UTC, pavel-kirienko commented on kucher/__init__.py
> +    THIRDPARTY_PATH.append(os.path.join(THIRDPARTY_PATH_ROOT, "dataclasses"))
This should be deleted

2022-06-20 10:33 UTC, pavel-kirienko commented on .gitmodules
>  	url = https://github.com/ericvsmith/dataclasses
This is no longer needed and should be deleted. Dataclasses are now part of the standard library.

2022-06-20 10:33 UTC, pavel-kirienko commented on kucher/__init__.py
> +    raise ImportError("A newer version of Python is required")
I suggest we delete this as python3.10 is used in all modern OSes. Or at least we bump the version number to 3.10.

2022-06-20 10:44 UTC, pavel-kirienko requested changes
Okay, I reviewed this against your autoformatted branch and it looks okay except for a couple of very minor changes. I reviewed the diff using this:

```
git difftool ca08f8f61f2219a3e15e0be1ff5726418aadf804 9d41eab7be6732bb9b34c2fd65b9b0397e8f99c7
```

Please in the future do not mix autoformatting with any non-trivial changes, ever, for obvious reasons.

2022-06-20 10:44 UTC, pavel-kirienko commented on kucher/model/device_model/device_info_view.py
> +    # _io: object
Please remove commented-out code

2022-06-20 10:44 UTC, pavel-kirienko commented on requirements-dev-windows.txt
> +pytest >= 7.*
Did you mean `==`?

2022-06-20 11:08 UTC, silverv commented on requirements-dev-windows.txt
> +pytest >= 7.*
yes

2022-06-20 11:45 UTC, pavel-kirienko commented
I see you fixed one occurrence of `# _io: object`, but there are more. Please remove all of them.

2022-06-20 12:03 UTC, pavel-kirienko approved these changes

2022-06-20 12:06 UTC, merged