Reset all registers button
Zubax/kucher pull request #6
Opened 2018-08-16 19:24 UTC by dimracer

I've added the button which resets all registers to defaults. It's more convenient than'Reset selected" registers button.

2018-08-16 19:36 UTC, pavel-kirienko requested changes

2018-08-16 19:36 UTC, pavel-kirienko commented on kucher/view/main_window/register_view_widget/__init__.py
> -
Dmitry, put the empty lines back, please.

2018-08-18 08:47 UTC, dimracer commented
corrected

2018-08-18 12:40 UTC, pavel-kirienko approved these changes

2018-08-18 12:40 UTC, pavel-kirienko commented
A confirmation dialog will be added later.

2018-08-18 12:40 UTC, merged